# Generated by Django 5.1.3 on 2024-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZakon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение'),
        ),
    ]
