# Generated by Django 5.1.3 on 2024-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZakon_app', '0003_alter_lawyer_options_alter_lawyer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='rating',
            field=models.IntegerField(default='0', verbose_name='Оценка'),
        ),
    ]
