# Generated by Django 5.1.3 on 2024-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZakon_app', '0005_lawyer_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.IntegerField(verbose_name='номер телефона'),
        ),
    ]
