# Generated by Django 5.1.3 on 2026-01-13 17:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя юриста')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание юриста')),
                ('status', models.CharField(default='Нету статуса', max_length=255, verbose_name='Статус юриста')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение')),
                ('closed', models.IntegerField(default='0', verbose_name='Дел закрыто')),
                ('rating', models.IntegerField(default='0', verbose_name='Оценка')),
                ('com', models.IntegerField(default='0', verbose_name='Отзывы')),
                ('succses', models.IntegerField(default=0, verbose_name='Успешно закрыто дел')),
                ('stazh', models.IntegerField(default='0', verbose_name='Стаж работы')),
                ('phone', models.IntegerField(verbose_name='номер телефона')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Резюме юриста',
                'verbose_name_plural': 'Резюме юристов',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='EZakon_app.lawyer')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
