# Generated by Django 5.1.3 on 2026-01-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZakon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(default='Номер юриста', max_length=20, verbose_name='номер телефона'),
        ),
    ]
