# Generated by Django 5.1.3 on 2026-01-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZakon_app', '0002_alter_lawyer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название закона')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер закона')),
                ('date_published', models.DateField(verbose_name='Дата опубликования')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('category', models.CharField(choices=[('civil', 'Гражданское право'), ('criminal', 'Уголовное право'), ('labor', 'Трудовое право'), ('family', 'Семейное право'), ('admin', 'Административное право'), ('tax', 'Налоговое право'), ('property', 'Право собственности'), ('constitutional', 'Конституционное право'), ('international', 'Международное право'), ('commercial', 'Коммерческое право'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('status', models.CharField(choices=[('active', 'Действующий'), ('archived', 'Архивированный'), ('draft', 'Черновик'), ('deprecated', 'Устаревший')], default='active', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Закон',
                'verbose_name_plural': 'Законы',
                'ordering': ['-date_published'],
                'indexes': [models.Index(fields=['category', '-date_published'], name='EZakon_app__categor_aae2fe_idx'), models.Index(fields=['status', 'is_active'], name='EZakon_app__status_92e3e1_idx'), models.Index(fields=['slug'], name='EZakon_app__slug_a71fad_idx')],
            },
        ),
        migrations.CreateModel(
            name='LawComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_comments', to='EZakon_app.law')),
            ],
            options={
                'verbose_name': 'Комментарий к закону',
                'verbose_name_plural': 'Комментарии к законам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField(verbose_name='Описание изменения')),
                ('previous_text', models.TextField(blank=True, verbose_name='Предыдущий текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='EZakon_app.law')),
            ],
            options={
                'verbose_name': 'История закона',
                'verbose_name_plural': 'Истории законов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_laws', to=settings.AUTH_USER_MODEL)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='EZakon_app.law')),
            ],
            options={
                'verbose_name': 'Избранный закон',
                'verbose_name_plural': 'Избранные законы',
                'unique_together': {('user', 'law')},
            },
        ),
    ]
